# Generated by Django 5.2.5 on 2025-08-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('service', models.CharField(choices=[('select a service', 'Select a Service'), ('portfolio website', 'Portfolio Website'), ('dynamic website', 'Dynamic Website'), ('e-commerce website', 'E-commerce Website'), ('custom solution', 'Custom Solution')], max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
